### ISSUE TITLE
Make README first-timer friendly

### ISSUE THREAD

**Issue by faraazahmad** [ubuntu/ubuntu-report#15]
Looking at README.md ,it is not very clear how to get started with contributing to this repo. It would be nice to have a Contributing section.

**Comment by didrocks** [comment]
I'm happy to help you getting into your first contribution, and then, we can craft together Contributing.md. Basically, the only requirements are:
- formatting using go fmt
- Everything covered by tests
- CI should pass (can run `go test ./...`).

Want to start drafting something around this?

**Comment by faraazahmad** [comment]
Sure! I'd love to

**Comment by didrocks** [comment]
I think you need some Go notions to be able to contribute to that project. I don't think we want to repeat how to setup a go project, but mainly link to it?

Install go: https://golang.org/doc/install
GOPATH setup and cloning the repo at the correct place: https://golang.org/doc/code.html
You don't need to get any dependencies.

Building the project is quite standard for this repo layout:
```
cd cmd/ubuntu-report
go build
```

**Comment by didrocks** [comment]
It seems you are using Go 1.6 which was released many years ago. Please use latest release, 1.10.

**Comment by didrocks** [comment]
Can you check you are running the correct Go version? (just run `go version`), it should picked up the vendored dependencies…

**Comment by faraazahmad** [comment]
```
$ pwd   
/home/.../ubuntu-report/cmd/ubuntu-report
$ go version
go version go1.10.2 linux/amd64
```

**Comment by didrocks** [comment]
and the project is checked out under `GOPATH`, correct?

**Comment by faraazahmad** [comment]
yes
```
$ pwd
/home/faraaz/go/ubuntu-report/cmd/ubuntu-report

```

**Comment by didrocks** [comment]
This isn't how a Go project is setup. You should use `go get github.com/ubuntu/ubuntu-report`, which will check it out under `/home/faraaz/go/src/github.com/ubuntu/ubuntu-report`.

**Comment by faraazahmad** [comment]
Ok it runs now, but how do i run it using `$ ubuntu-report`

**Comment by didrocks** [comment]
I think you didn’t have the time to look at it again. Closing as nobody else is complaining about the README itself.
