### ISSUE TITLE
Software and update option in system setting is not there after upgrading ubuntu18 from 16

### ISSUE THREAD

**Issue by rahulsharma11** [ubuntu/ubuntu-report#17]
Hi,
I can't see the software and update option in system setting in Ubuntu18 upgrade.
Any help?
thanks.

**Comment by didrocks** [comment]
hey!

"ubuntu-report" is a tool part of ubuntu, it's not about reporting bugs on ubuntu, sorry you got confused :)

Please check for user support to get more info: https://www.ubuntu.com/support/community-support
