### ISSUE TITLE
Lockscreen shortcut doesn't work in new upgrade

### ISSUE THREAD

**Issue by cseas** [ubuntu/ubuntu-report#31]
Not sure if this is the best place to report this.

The shortcut to lock the screen `Windows + L` used to work fine in Ubuntu 18.04 LTS but since I've upgraded to Ubuntu 20.04 LTS, that shortcut doesn't seem to be working anymore.

**Expected behaviour:** `Windows + L` should lock the screen, but doesn't.

**Comment by didrocks** [comment]
> Not sure if this is the best place to report this.
Indeed, this is not :)

This project is about the telemetry features for ubuntu.

You need to report your bug with `ubuntu-bug gnome-settings-daemon` which will file with all needed information from your system a bug on launchpad.
