### ISSUE TITLE
Latest ubuntu server for Raspberry Pi does not include can-j1939 module by default

### ISSUE THREAD

**Issue by ManishKakra** [ubuntu/ubuntu-report#35]
Hello,
I have tried below two images for raspberry pi and both does not seem to include the can-j1939 modules by default.
ubuntu-20.04.2-preinstalled-server-arm64+raspi.img and
ubuntu-20.10-preinstalled-server-arm64+raspi.img
More details on J1939 is here https://www.kernel.org/doc/html/latest/networking/j1939.html

In order to use this, module I will have to rebuild the kernel with can-j1939 module included.

Is that something that was supported to be by default in recent kernel images ? 
Is there any other ubuntu image version that includes it by default? 

Please suggest. Thank you in advance.

Thanks,
Manish K

**Comment by didrocks** [comment]
Please report this bug on launchpad.net, which is where ubuntu bugs needs to be reported.

This project is about metrics collection on the ubuntu project, nothing related to raspberry pi.
