### ISSUE TITLE
Internet is too slow in many times with Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter when I using ubuntu 20.04

### ISSUE THREAD

**Issue by rthiru96** [ubuntu/ubuntu-report#36]
I can able to use the internet with full speed at the beginning(initially(20Mbps)) after sometime(after using 30-45 minutes) net speed is getting extremely slow(like 14kbps-8kbps) [I have noticed this always like more than 15-20 times]. My machine is Dell G3 15 3590 configured with Qualcomm Atheros QCA9377 802.11ac, 16 GB ram and Intel® Core™ i5-9300H CPU( https://www.dell.com/support/home/en-us/product-support/servicetag/0-YUFGdHU4cTJoc3BCVU5iMldVRkxVUT090/overview). I like to mention I have the same issue with official ubuntu 20.04.1 lts but linux lite they have same ubuntu inside that but I haven't face any internet issues with linux lite. I can able make sure my internet connection speed is always same because my macbook doesn't have any issues.

**Comment by didrocks** [comment]
Hey, Please report this bug on https://launchpad.net, which is where ubuntu bugs needs to be reported. You can find more information on https://help.ubuntu.com/community/ReportingBugs

This project is about metrics collection on the ubuntu project, as the README is stating.
