### ISSUE TITLE
My printer don't work correctily and fully!

### ISSUE THREAD

**Issue by eudavidcesar** [ubuntu/ubuntu-report#39]
Notebook Dell Inspiron 14 5468, Intel Core i5 and 4Gb on RAM. I use the Ubuntu 20.04 LTS.

My printer don't work correctily and fully, I use a ***EPSON L395*** and when I try print a file in both sides of paper this isn't work. I still search for solutions many things, but my veredict is: The driver avalible don't work fine. In my print I can scan, print with all colors and configure a half of things in it. What I need to learn to make drivers to Ubuntu and how I can contribute to this distro?

Thanks for attention! Sorry for erros in my first issues and my poor english.

P.S. 

I went to the CUPS in localhost, but when I try use the command in bottom:

```sh
lp -o sides=two-sided-long-edge
```
But will still printing in one side, so the driver don't recognize the both side print instruction.

**Comment by didrocks** [comment]
This repository is about telemetry in ubuntu, not reporting bugs against ubuntu. For this, please follow this page: https://help.ubuntu.com/community/ReportingBugs
