### ISSUE TITLE
Using LXD the CONFIG_TCP_MD5SIG=y on virtual machines via --vm is missing from Ubuntu images /boot/ dir

### ISSUE THREAD

**Issue by jeremybusk** [ubuntu/ubuntu-report#47]
Using Ubuntu images on Ubuntu 22.04 or 20.04 in /boot/config... CONFIG_TCP_MD5SIG=y is missing (not set)
In Bullseye CONFIG_TCP_MD5SIG=y exists. Why not enabled in Ubuntu images?

lxc launch images:debian/11 bullseye-vm --vm 
( CONFIG_TCP_MD5SIG=y)

lxc launch ubuntu:22.04 jammy-vm --vm 
(CONFIG_TCP_MD5SIG is not set)

5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

snap list | grep lxd
lxd         5.13-cea5ee2  24758  latest/stable  canonical**

Here are my image lists

lxc image list
+-------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 | ARCHITECTURE |      TYPE       |   SIZE   |         UPLOAD DATE          |
+-------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+------------------------------+
|       | 5ea9ef591ecb | no     | ubuntu 20.04 LTS amd64 (release) (20230420) | x86_64       | CONTAINER       | 435.71MB | Apr 21, 2023 at 5:22am (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+------------------------------+
|       | 23d0fe2e0a78 | no     | ubuntu 22.04 LTS amd64 (release) (20230424) | x86_64       | CONTAINER       | 446.44MB | Apr 25, 2023 at 7:59pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+------------------------------+
|       | cedbb64a0a05 | no     | Debian bullseye amd64 (20230425_05:52)      | x86_64       | VIRTUAL-MACHINE | 298.69MB | Apr 25, 2023 at 8:04pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+------------------------------+
|       | e10f4daafdf1 | no     | ubuntu 20.04 LTS amd64 (release) (20230420) | x86_64       | VIRTUAL-MACHINE | 600.63MB | Apr 21, 2023 at 5:23am (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+------------------------------+
|       | f1dd0e76efe8 | no     | ubuntu 22.04 LTS amd64 (release) (20230424) | x86_64       | VIRTUAL-MACHINE | 626.06MB | Apr 25, 2023 at 7:55pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+------------------------------+

**Comment by didrocks** [comment]
I guess there is a mislead in the repo. This is the repo for the metrics collection tool in ubuntu, not ubuntu images. I suggest you to open this bug on launchpad, against the ubuntu project (https://launchpad.net/), or, for a more guided bug reporting, run `ubuntu-bug`
